# Generated by Django 4.0.4 on 2023-09-24 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CompositionInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compositions.composition')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compositions.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='CompositionComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('child_composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_composition_set', to='compositions.composition')),
                ('parent_composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_composition_set', to='compositions.composition')),
            ],
        ),
        migrations.AddField(
            model_name='composition',
            name='compositions',
            field=models.ManyToManyField(related_name='child_compositions', through='compositions.CompositionComposition', to='compositions.composition'),
        ),
        migrations.AddField(
            model_name='composition',
            name='insumos',
            field=models.ManyToManyField(through='compositions.CompositionInsumo', to='compositions.insumo'),
        ),
    ]
