# Generated by Django 4.0.4 on 2023-09-24 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='cost',
        ),
        migrations.AddField(
            model_name='composition',
            name='codigo',
            field=models.CharField(default=1001, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insumo',
            name='codigo',
            field=models.CharField(default=1002, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CostHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compositions.insumo')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compositions.state')),
            ],
        ),
        migrations.AddIndex(
            model_name='costhistory',
            index=models.Index(fields=['insumo', 'state', 'month_year'], name='composition_insumo__e9acda_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='costhistory',
            unique_together={('insumo', 'state', 'month_year')},
        ),
    ]
