# Generated by Django 4.0.4 on 2023-09-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0005_alter_compositioncomposition_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='currentcost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
