# Generated by Django 4.0.4 on 2023-09-26 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0007_alter_compositioncomposition_child_composition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositioncomposition',
            name='child_composition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_composition_through', to='compositions.composition'),
        ),
    ]
