# Generated by Django 4.0.4 on 2023-09-26 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0008_alter_compositioncomposition_child_composition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='compositions',
            field=models.ManyToManyField(related_name='parent_compositions', through='compositions.CompositionComposition', to='compositions.composition'),
        ),
        migrations.AlterField(
            model_name='compositioncomposition',
            name='child_composition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositionparent_set', to='compositions.composition'),
        ),
        migrations.AlterField(
            model_name='compositioncomposition',
            name='parent_composition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositionchild_set', to='compositions.composition'),
        ),
    ]
