# Generated by Django 4.0.4 on 2023-09-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0009_alter_composition_compositions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='comp_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=25),
        ),
    ]
