# Generated by Django 4.0.4 on 2023-10-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0010_composition_comp_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='composition',
            name='unit',
            field=models.CharField(max_length=10),
        ),
    ]
